#!/usr/bin/python3

# accept stdin/pipe/argument, also accept multiline
# $1: split char
# $2: select n-th string, default None
# $3: string to be splitted, default None
# usage:
#   $ ./str-split '.' 'www.google.com'
#   www google com
#   $ ./str-split '.' 1 'www.google.com'
#   www
#   $ echo 'www.google.com' | ./str-split '.'
#   www google com
#   $ echo 'www.google.com' | ./str-split '.' 1
#   www

import sys

args = sys.argv

if sys.stdin.isatty():
    if len(args) == 1:
        print('[Error] No input', file=sys.stderr)
        exit(-1)
    s = args[-1]
    ARG_ANCH_SPLIT = 2
    ARG_ANCH_SELECT = 3
    _iter = s.split('\n')
else:
    ARG_ANCH_SPLIT = 1
    ARG_ANCH_SELECT = 2
    _iter = sys.stdin.readlines()

_split = ' '
if len(args) > ARG_ANCH_SPLIT:
    _split = args[1]

_select = None
if len(args) > ARG_ANCH_SELECT:
    _select = int(args[2])

for line in _iter:
    line = line.rstrip()
    line = line.split(_split)
    if _select is None:
        for c in line:
            print(c, end=' ', file=sys.stdout)
        print(file=sys.stdout)
    else:
        print(line[_select-1], file=sys.stdout)